import Head from "next/head";
import { GetServerSideProps } from "next";
import HomePage from "@/src/components/home/home-page";

export default function Home(props: any) {
  const { data } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { events_categories } = await import("../data/data.json");

  return {
    props: {
      data: events_categories,
    },
  };
};
